[package]
edition = "2024"
name = "audio-driver"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15"
rtrb = "0.3.2"
thiserror = "2.0.11"
